# template privsyn config file

[path_params]
meta_data = "./datasets/insurance/insurance.json"
raw_data = "./datasets/insurance/insurance.csv"
train_data = "./datasets/insurance/train.csv"
val_data = "./datasets/insurance/val.csv"
test_data = "./datasets/insurance/test.csv"
loss_record = "./exp/insurance/privsyn/loss.csv"
out_model = "./exp/insurance/privsyn/privsyn.pkl"
out_data = "./exp/insurance/privsyn/insurance.csv"
fidelity_result = "./exp/insurance/privsyn/fidelity_result.csv"
fidelity_train_result = "./exp/insurance/privsyn/fidelity_train_result.csv"
privacy_result = "./exp/insurance/privsyn/privacy_result.csv"
utility_result = "./exp/insurance/privsyn/utility_result.csv"

[model_params]
epsilon = 5 # infinite privacy budget
delta = 1e-10
max_bins = 100
update_iterations = 50
one-way-publish = 0.1
two-way-select = 0.1
two-way-publish = 0.8
combine = 0.1


[sample_params]
num_samples = 0 # sample the same number of samples as the train+val data