# template privsyn config file

[path_params]
meta_data = "./datasets/robot/robot.json"
raw_data = "./datasets/robot/robot.csv"
train_data = "./datasets/robot/train.csv"
val_data = "./datasets/robot/val.csv"
test_data = "./datasets/robot/test.csv"
loss_record = "./exp/robot/privsyn/loss.csv"
out_model = "./exp/robot/privsyn/privsyn.pkl"
out_data = "./exp/robot/privsyn/robot.csv"
fidelity_result = "./exp/abalone/privsyn/fidelity_result.csv"
fidelity_train_result = "./exp/abalone/privsyn/fidelity_train_result.csv"
privacy_result = "./exp/abalone/privsyn/privacy_result.csv"
utility_result = "./exp/abalone/privsyn/utility_result.csv"

[model_params]
epsilon = 0.2
delta = 1e-10
max_bins = 100
update_iterations = 50
one-way-publish = 0.1
two-way-select = 0.1
two-way-publish = 0.8
combine = 0.1
client_num = 1

[sample_params]
num_samples = 0 # sample the same number of samples as the train+val data