# template privsyn config file

[path_params]
meta_data = "./datasets/shoppers/shoppers.json"
raw_data = "./datasets/shoppers/shoppers.csv"
train_data = "./datasets/shoppers/train.csv"
val_data = "./datasets/shoppers/val.csv"
test_data = "./datasets/shoppers/test.csv"
loss_record = "./exp/shoppers/fed_privsyn_baseline/loss.csv"
out_model = "./exp/shoppers/fed_privsyn_baseline/fed_privsyn.pkl"
out_data = "./exp/shoppers/fed_privsyn_baseline/shoppers.csv"
fidelity_result = "./exp/shoppers/fed_privsyn_baseline/fidelity_result.csv"
fidelity_train_result = "./exp/shoppers/fed_privsyn_baseline/fidelity_train_result.csv"
privacy_result = "./exp/shoppers/fed_privsyn_baseline/privacy_result.csv"
utility_result = "./exp/shoppers/fed_privsyn_baseline/utility_result.csv"

[model_params]
epsilon = 5 # privacy budget
delta = 1e-10
max_bins = 100
update_iterations = 50
noise_to_one_way_marginal = 0
noise_to_two_way_marginal = 0
two-way-publish = 1
client_num = 5
disttype = "uniform"


[sample_params]
num_samples = 0 # sample the same number of samples as the train+val data