# template privsyn config file

[path_params]
meta_data = "./datasets/insurance/insurance.json"
raw_data = "./datasets/insurance/insurance.csv"
train_data = "./datasets/insurance/train.csv"
val_data = "./datasets/insurance/val.csv"
test_data = "./datasets/insurance/test.csv"
loss_record = "./exp/insurance/fed_privsyn/loss.csv"
out_model = "./exp/insurance/fed_privsyn/fed_privsyn.pkl"
out_data = "./exp/insurance/fed_privsyn/insurance.csv"
fidelity_result = "./exp/insurance/fed_privsyn/fidelity_result.csv"
fidelity_train_result = "./exp/insurance/fed_privsyn/fidelity_train_result.csv"
privacy_result = "./exp/insurance/fed_privsyn/privacy_result.csv"
utility_result = "./exp/insurance/fed_privsyn/utility_result.csv"

[model_params]
epsilon = 0.2 # privacy budget
delta = 1e-10
max_bins = 100
update_iterations = 50
noise_to_one_way_marginal = 0.3
noise_to_two_way_marginal = 0.3
two-way-publish = 0.4
client_num = 2
disttype = "uniform"

[sample_params]
num_samples = 0 # sample the same number of samples as the train+val data