# template privsyn config file

[path_params]
meta_data = "./datasets/adult/adult.json"
raw_data = "./datasets/adult/adult.csv"
train_data = "./datasets/adult/train.csv"
val_data = "./datasets/adult/val.csv"
test_data = "./datasets/adult/test.csv"
loss_record = "./exp/adult/fed_privsyn/loss.csv"
out_model = "./exp/adult/fed_privsyn/fed_privsyn.pkl"
out_data = "./exp/adult/fed_privsyn/adult.csv"
fidelity_result = "./exp/fed_privsyn/fidelity_result.csv"
fidelity_train_result = "./exp/fed_privsyn/fidelity_train_result.csv"
privacy_result = "./exp/fed_privsyn/privacy_result.csv"
utility_result = "./exp/fed_privsyn/utility_result.csv"

[model_params]
epsilon = 10 # infinite privacy budget
delta = 3.4498908254380166e-11
max_bins = 100
update_iterations = 50
noise_to_one_way_marginal = 0.2
noise_to_two_way_marginal = 0.2
two-way-publish = 0.6


[sample_params]
num_samples = 0 # sample the same number of samples as the train+val data