# template privsyn config file

[path_params]
meta_data = "./datasets/bean/bean.json"
raw_data = "./datasets/bean/bean.csv"
train_data = "./datasets/bean/train.csv"
val_data = "./datasets/bean/val.csv"
test_data = "./datasets/bean/test.csv"
loss_record = "./exp/bean/privsyn/loss.csv"
out_model = "./exp/bean/privsyn/privsyn.pkl"
out_data = "./exp/bean/privsyn/bean.csv"
fidelity_result = "./exp/bean/privsyn/fidelity_result.csv"
fidelity_train_result = "./exp/bean/privsyn/fidelity_train_result.csv"
privacy_result = "./exp/bean/privsyn/privacy_result.csv"
utility_result = "./exp/bean/privsyn/utility_result.csv"

[model_params]
epsilon = 5
delta = 1e-10
max_bins = 100
update_iterations = 50
one-way-publish = 0.1
two-way-select = 0.1
two-way-publish = 0.8
combine = 0.1
client_num = 1


[sample_params]
num_samples = 0 # sample the same number of samples as the train+val data