# template privsyn config file

[path_params]
meta_data = "./datasets/bean/bean.json"
raw_data = "./datasets/bean/bean.csv"
train_data = "./datasets/bean/train.csv"
val_data = "./datasets/bean/val.csv"
test_data = "./datasets/bean/test.csv"
loss_record = "./exp/bean/fed_privsyn_adaptive/loss.csv"
out_model = "./exp/bean/fed_privsyn_adaptive/fed_privsyn.pkl"
out_data = "./exp/bean/fed_privsyn_adaptive/bean.csv"
fidelity_result = "./exp/bean/fed_privsyn_adaptive/fidelity_result.csv"
fidelity_train_result = "./exp/bean/fed_privsyn_adaptive/fidelity_train_result.csv"
privacy_result = "./exp/bean/fed_privsyn_adaptive/privacy_result.csv"
utility_result = "./exp/bean/fed_privsyn_adaptive/utility_result.csv"

[model_params]
epsilon = 5 # infinite privacy budget
delta = 1e-10
max_bins = 100
update_iterations = 50
noise_to_one_way_marginal = 0.2
noise_to_two_way_marginal = 0.2
two-way-publish = 0.6
client_num = 10


[sample_params]
num_samples = 0 # sample the same number of samples as the train+val data