# template privsyn config file

[path_params]
meta_data = "./datasets/obesity/obesity.json"
raw_data = "./datasets/obesity/obesity.csv"
train_data = "./datasets/obesity/train.csv"
val_data = "./datasets/obesity/val.csv"
test_data = "./datasets/obesity/test.csv"
loss_record = "./exp/obesity/fed_privsyn_baseline/loss.csv"
out_model = "./exp/obesity/fed_privsyn_baseline/fed_privsyn.pkl"
out_data = "./exp/obesity/fed_privsyn_baseline/obesity.csv"
fidelity_result = "./exp/obesity/fed_privsyn_baseline/fidelity_result.csv"
fidelity_train_result = "./exp/obesity/fed_privsyn_baseline/fidelity_train_result.csv"
privacy_result = "./exp/obesity/fed_privsyn_baseline/privacy_result.csv"
utility_result = "./exp/obesity/fed_privsyn_baseline/utility_result.csv"

[model_params]
epsilon = 5
delta = 1e-10
max_bins = 100
update_iterations = 50
noise_to_one_way_marginal = 0
noise_to_two_way_marginal = 0
two-way-publish = 1
client_num = 5
disttype = "uniform"


[sample_params]
num_samples = 0 # sample the same number of samples as the train+val data